---
title: "Diffraction_Data"
author: "Kayla Tumbaga"
date: "April 16, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r calculations}
diffractiondata <- read.table(header=TRUE, text="
Fringe   Diameter(um) Wavelength(nm)   Distance(cm)   
1        88.64        650              2.2
1        975          650              2.0
1        43.33        650              1.5
1        58.56        640              1.0
2        86.67        650              4.5
2        86.67        650              4.5
2        52.00        650              2.5
2        58.56        640              2.0
3        82.39        650              7.1
3        90.0         650              6.5
3        51.3         650              3.8
3        79.85        640              2.2
4        84.78        650              9.2
4        91.76        650              8.5
4        54.16        650              4.8
4        83.65        640              2.8
average  79.32        648              N/A")    
```
Table 1.
Combined data of all three trials completed


```{r calculations}
averagediameter <- read.table(header=TRUE, text="
Group     Average_Diameter(um)   Color
1           196.78               brown
2           96.4                 blonde
3           161.76               brown
4           85.62                brown
5           30.58                red
6           122.8                red")
```
Table 2. The Average Diameter of Hair for Multiple Groups