<<<<<<< HEAD
---
title: "PythonCode"
author: "Nick Sitter"
date: "April 30, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file was written to code different processes such as calculating averages, creating boxplots, and performing an ANOVA. Notable tables can be seen below.

Table 1. Combined data of all trials completed

diffractiondata = read.table(header=TRUE, text="
Fringe   Diameter(um) Wavelength(nm)   Distance(cm)   
1        88.64        650              2.2
1        975          650              2.0
1        43.33        650              1.5
1        58.56        640              1.0
2        86.67        650              4.5
2        86.67        650              4.5
2        52.00        650              2.5
2        58.56        640              2.0
3        82.39        650              7.1
3        90.0         650              6.5
3        51.3         650              3.8
3        79.85        640              2.2
4        84.78        650              9.2
4        91.76        650              8.5
4        54.16        650              4.8
4        83.65        640              2.8
average  79.32        648              N/A") 

Table 2. Average Diameter by Hair Color
 
Group     Average Diameter(um)   Color
1           196.78               brown
2           96.4                 blonde
3           161.76               brown
4           85.62                brown
5           30.58                red
6           122.8                red")

Code Block 1 - Averages Diameters of Fringe 1

```{python}
def avg(numList):
    avg = sum(numList) / len(numList)
    return avg

Fringe1 = [88, 975, 43.33, 58.56]
print(avg(Fringe1))
```

Code Block 2 - Averages Diameters of Fringe 2

```{python}
def avg(numList):
    avg = sum(numList) / len(numList)
    return avg

Fringe2 = [86.67, 86.67,52, 58.56]
print(avg(Fringe2))
```

Code Block 3 - Averages Diameters of Fringe 3

```{python}
def avg(numList):
    avg = sum(numList) / len(numList)
    return avg

Fringe3 = [82.39, 90, 51.3, 79.85]
print(avg(Fringe3))
```

Code Block 4 - Averages Diameters of Fringe 4

```{python}
def avg(numList):
    avg = sum(numList) / len(numList)
    return avg

Fringe4 = [84.78, 91.76, 54.16, 83.65]
print(avg(Fringe4))
```

Code Block 5 - Creates a png File of a Boxplot

```{python}
import matplotlib as mpl 
mpl.use('agg')
import matplotlib.pyplot as plt 
Fringe1 = (88, 975, 43.33, 58.56)
Fringe2 = (86.67, 86.67,52, 58.56)
Fringe3 = (82.39, 90, 51.3, 79.85)
Fringe4 = (84.78, 91.76, 54.16, 83.65)
data_to_plot = [Fringe1, Fringe2, Fringe3, Fringe4]
fig = plt.figure(1, figsize=(9, 6))
ax = fig.add_subplot(111)
boxplot = ax.boxplot(data_to_plot)
ax.set_title('Boxplot of Diameters by Fringe')
ax.set_xticklabels(['Fringe 1', 'Fringe 2', 'Fringe 3', 'Fringe 4'])
ax.set_ylabel('Diameter (um)')
fig.savefig('fig1.png', bbox_inches='tight')
```


Code Block 6 - Gives ANOVA Table Between The Different Fringes

```{python}
import statsmodels.api as sm 
from statsmodels.formula.api import ols
import pandas as pd
datafile = "DiffractionDataTable1.csv"
data = pd.read_csv(datafile)
mod = ols('Fringe ~ Diameter', data=data).fit()
aov_table = sm.stats.anova_lm(mod, typ=2)
print(aov_table)
```